// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ8oXHL7R8qxazwRHqlQ6Hucas5nQIzmk',
    appId: '1:678354093150:web:13a9921b9160ead1bf20cf',
    messagingSenderId: '678354093150',
    projectId: 'flutter-learning-app-5f2a5',
    authDomain: 'flutter-learning-app-5f2a5.firebaseapp.com',
    storageBucket: 'flutter-learning-app-5f2a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_wyktx5qTVYw4Pr_p3D1fNfcO-J_eHlc',
    appId: '1:678354093150:android:082655246547ef55bf20cf',
    messagingSenderId: '678354093150',
    projectId: 'flutter-learning-app-5f2a5',
    storageBucket: 'flutter-learning-app-5f2a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8dbMurAs5I5rU8oIgnjFYsegtGJzy8gQ',
    appId: '1:678354093150:ios:c04264cb1b83e0acbf20cf',
    messagingSenderId: '678354093150',
    projectId: 'flutter-learning-app-5f2a5',
    storageBucket: 'flutter-learning-app-5f2a5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8dbMurAs5I5rU8oIgnjFYsegtGJzy8gQ',
    appId: '1:678354093150:ios:c04264cb1b83e0acbf20cf',
    messagingSenderId: '678354093150',
    projectId: 'flutter-learning-app-5f2a5',
    storageBucket: 'flutter-learning-app-5f2a5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ8oXHL7R8qxazwRHqlQ6Hucas5nQIzmk',
    appId: '1:678354093150:web:d88c6a6328c7b32bbf20cf',
    messagingSenderId: '678354093150',
    projectId: 'flutter-learning-app-5f2a5',
    authDomain: 'flutter-learning-app-5f2a5.firebaseapp.com',
    storageBucket: 'flutter-learning-app-5f2a5.firebasestorage.app',
  );
}
